-- MySQL Script generated by MySQL Workbench
-- 05/28/15 12:15:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema transport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transport` DEFAULT CHARACTER SET utf8 ;
USE `transport` ;

-- -----------------------------------------------------
-- Table `transport`.`carbrend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transport`.`carbrend` (
  `brendId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `brendName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`brendId`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `transport`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transport`.`car` (
  `carId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `carCategory` BIGINT(20) NULL DEFAULT NULL,
  `carModel` VARCHAR(255) NULL DEFAULT NULL,
  `passengers` BIGINT(20) NULL DEFAULT NULL,
  `brendId` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`carId`),
  UNIQUE INDEX `UK_dm51d441jdu7i4ntg7yyqtkt3` (`carModel` ASC),
  INDEX `FK_dot2j8bh7dvmdljthidc5jfku` (`brendId` ASC),
  CONSTRAINT `FK_dot2j8bh7dvmdljthidc5jfku`
    FOREIGN KEY (`brendId`)
    REFERENCES `transport`.`carbrend` (`brendId`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `transport`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transport`.`users` (
  `userId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `disabled` BIT(1) NOT NULL,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `ready` BIT(1) NOT NULL,
  `userRole` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `carId` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `UK_r43af9ap4edm43mmtq01oddj6` (`username` ASC),
  INDEX `FK_d00307p17ph4u1trag9rk671p` (`carId` ASC),
  CONSTRAINT `FK_d00307p17ph4u1trag9rk671p`
    FOREIGN KEY (`carId`)
    REFERENCES `transport`.`car` (`carId`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `transport`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transport`.`orders` (
  `orderId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `carCategory` BIGINT(20) NULL DEFAULT NULL,
  `date` TINYBLOB NULL DEFAULT NULL,
  `fromWhere` VARCHAR(255) NULL DEFAULT NULL,
  `passengers` BIGINT(20) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `toWhere` VARCHAR(255) NULL DEFAULT NULL,
  `userId` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`orderId`),
  INDEX `FK_2gcgbfud7n5ixb7qqb6nuaqxw` (`userId` ASC),
  CONSTRAINT `FK_2gcgbfud7n5ixb7qqb6nuaqxw`
    FOREIGN KEY (`userId`)
    REFERENCES `transport`.`users` (`userId`))
ENGINE = InnoDB
AUTO_INCREMENT = 928
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
